Feature/cookie name option
auth0/auth0-aspnetcore-authentication pull request #98
Opened 2023-02-11 22:39 UTC by nquandt

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Add the ability to specify the cookie scheme used

### Testing

Create aspnet project with custom cookie.

```csharp
services
  .AddAuthentication()
  .AddCookie("MyCookieScheme", () => {})
  .AddAuth0WebAppAuthentication(options => {
    options.CookieName = "MyCookieScheme";
  });
- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `main`

2023-02-13 08:47 UTC, frederikprijck requested changes
Thanks for the changes! Added a couple of small comments to ensure we keep the PR focussed.

2023-02-13 08:47 UTC, frederikprijck commented on src/Auth0.AspNetCore.Authentication/ServiceCollectionExtensions.cs
> +            }
I dont think we need this change. If you do not want to our SDK to call `AddAuthentication`, you should not use our ServiceCollectionExtensions, you should use our `AuthenticationBuilderExtensions`. 

Instead, we should focus on just the cookieName in this code. I believe we should be dropping the `setDefaultSchemes` and rollback most of these changes but only ensure we set the cookie to `auth0Options.CookieName`.

2023-02-13 08:47 UTC, frederikprijck commented on src/Auth0.AspNetCore.Authentication/Auth0WebAppOptions.cs
> +        public string CookieName { get; set; } = CookieAuthenticationDefaults.AuthenticationScheme;
Would it make sense to name this `CookieAuthenticationScheme` ?

2023-02-13 15:23 UTC, nquandt commented
I made some updates based on your comments! Thanks for reviewing, and thanks for the tip about using the `AuthenticationBuilderExtensions` instead of the `ServiceCollectionExtensions`

2023-02-17 10:37 UTC, frederikprijck approved these changes
Thanks for the work here, I patched the PR to add something that was missing, and added a couple of tests to verify it works as intended.

2023-03-09 10:11 UTC, merged